name: Publish and Test NPM Package  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Setup Node.js environment  
        uses: actions/setup-node@v1  
        with:  
          node-version: 20 
  
      - name: Install dependencies  
        run: npm ci  
  
      - name: Build package  
        run: npm run build  
  
      - name: Test package  
        run: npm run test  
  
      - name: Publish package  
        uses: JS-DevTools/npm-publish@v1  
        with:  
          token: ${{ secrets.NPM_AUTH_TOKEN }} 